#' Rebuild a rooted binary IQ-TREE by splitting the outgroup branch equally
#'
#' @description
#' Rebuild a rooted binary tree by identifying a specified outgroup tip,
#' extracting its original pendant branch length `L`, removing its original
#' occurrence from the root, and rebuilding the root as
#' `(<ingroup>:L/2,<outgroup>:L/2);`.
#'
#' The function accepts a tree file path, a `phylo` object, or a `treedata`
#' object. By default it returns a `treedata` object. Writing the rebuilt Newick
#' tree to disk is optional.
#'
#' @param tree A path to a tree file, a `phylo` object, or a `treedata` object.
#' @param outgroup_label Character scalar. Exact tip label of the outgroup.
#' @param digits Integer scalar. Number of decimal places used when formatting
#'   branch lengths in Newick output. Default: `8`.
#' @param return Character scalar. One of `"treedata"`, `"newick"`, or
#'   `"phylo"`. Default: `"treedata"`.
#' @param write Logical. If `TRUE`, write the rebuilt tree to disk.
#'   Default: `FALSE`.
#' @param file Optional output file path when `write = TRUE`. If `tree` is a
#'   file path and `file = NULL`, the output path is generated by replacing the
#'   extension with `.bi.treefile`.
#' @param overwrite Logical. If `FALSE`, error if `file` already exists.
#'   Default: `FALSE`.
#' @param preserve_data Logical. Reserved for future richer `treedata` support.
#'   The current implementation rebuilds topology and branch lengths, but does
#'   not reattach auxiliary node or tip annotations after topology changes.
#' @param verbose Logical. If `TRUE`, print progress messages.
#'   Default: `FALSE`.
#'
#' @return
#' Depending on `return`, one of:
#' - a `treeio::treedata` object
#' - a Newick string
#' - a `phylo` object
#'
#' If `write = TRUE`, the rebuilt Newick tree is also written to disk.
#'
#' @details
#' The outgroup tip must be attached directly to the current root, and the
#' outgroup branch must have a finite, non-negative branch length. This keeps
#' the operation explicit: the function does not search for or reroot by an
#' outgroup elsewhere in the tree.
#'
#' @examples
#' \dontrun{
#' td2 <- make_binary_iqtree("example.treefile", "Outgroup_Sp")
#'
#' nwk <- make_binary_iqtree(
#'   "example.treefile",
#'   "Outgroup_Sp",
#'   return = "newick"
#' )
#'
#' make_binary_iqtree(
#'   "example.treefile",
#'   "Outgroup_Sp",
#'   write = TRUE,
#'   file = "example.bi.treefile"
#' )
#' }
#'
#' @export
make_binary_iqtree <- function(
        tree,
        outgroup_label,
        digits = 8,
        return = c("treedata", "newick", "phylo"),
        write = FALSE,
        file = NULL,
        overwrite = FALSE,
        preserve_data = TRUE,
        verbose = FALSE
) {
    return <- match.arg(return)

    if (!is.character(outgroup_label) ||
        length(outgroup_label) != 1L ||
        is.na(outgroup_label) ||
        identical(outgroup_label, "")) {
        stop("`outgroup_label` must be a single non-empty character string.")
    }

    if (!is.numeric(digits) ||
        length(digits) != 1L ||
        is.na(digits) ||
        digits < 0 ||
        digits != floor(digits)) {
        stop("`digits` must be a single non-negative integer.")
    }
    digits <- as.integer(digits)

    for (arg_name in c("write", "overwrite", "preserve_data", "verbose")) {
        value <- get(arg_name, inherits = FALSE)
        if (!is.logical(value) || length(value) != 1L || is.na(value)) {
            stop("`", arg_name, "` must be TRUE or FALSE.")
        }
    }

    input_file <- NULL

    if (is.character(tree) && length(tree) == 1L && !is.na(tree)) {
        input_file <- tree
        if (!file.exists(input_file)) {
            stop("Tree file does not exist: ", input_file)
        }
        phy <- ape::read.tree(file = input_file)
    } else if (inherits(tree, "treedata")) {
        phy <- ape::as.phylo(tree)
        if (preserve_data && verbose) {
            message(
                "`treedata` auxiliary annotations are not reattached after ",
                "topology reconstruction."
            )
        }
    } else if (inherits(tree, "phylo")) {
        phy <- tree
    } else {
        stop(
            "`tree` must be a file path, a `phylo` object, or a ",
            "`treedata` object."
        )
    }

    if (inherits(phy, "multiPhylo")) {
        stop("`tree` contains multiple trees; please provide exactly one tree.")
    }
    if (!inherits(phy, "phylo")) {
        stop("Could not convert `tree` to a `phylo` object.")
    }
    if (is.null(phy$edge) || ncol(phy$edge) != 2L) {
        stop("Input tree has an invalid `edge` matrix.")
    }
    if (is.null(phy$edge.length) ||
        length(phy$edge.length) != nrow(phy$edge)) {
        stop("Input tree must contain one branch length for each edge.")
    }

    tip_hits <- which(phy$tip.label == outgroup_label)
    if (length(tip_hits) == 0L) {
        stop("Outgroup tip was not found in the tree: ", outgroup_label)
    }
    if (length(tip_hits) > 1L) {
        stop("Outgroup tip label is duplicated in the tree: ", outgroup_label)
    }
    outgroup_tip <- tip_hits[[1L]]

    outgroup_edge <- which(phy$edge[, 2L] == outgroup_tip)
    if (length(outgroup_edge) != 1L) {
        stop(
            "Could not identify exactly one edge for outgroup tip: ",
            outgroup_label
        )
    }

    root_candidates <- setdiff(
        unique(phy$edge[, 1L]),
        unique(phy$edge[, 2L])
    )
    if (length(root_candidates) != 1L) {
        stop("Could not identify a single root in the input tree.")
    }
    root_node <- root_candidates[[1L]]

    if (phy$edge[outgroup_edge, 1L] != root_node) {
        stop(
            "`outgroup_label` must be attached directly to the current root. ",
            "Reroot the tree first if the outgroup is nested elsewhere."
        )
    }

    outgroup_length <- phy$edge.length[outgroup_edge]
    if (!is.finite(outgroup_length) || outgroup_length < 0) {
        stop("Outgroup branch length must be finite and non-negative.")
    }

    ntip <- length(phy$tip.label)
    nnode <- phy$Nnode
    new_root <- ntip + 1L
    shifted_old_root <- root_node + 1L

    remap_internal_nodes <- function(x) {
        is_internal <- x > ntip
        x[is_internal] <- x[is_internal] + 1L
        x
    }

    keep_edges <- seq_len(nrow(phy$edge))[-outgroup_edge]
    rebuilt_edges <- phy$edge[keep_edges, , drop = FALSE]
    rebuilt_edges[, 1L] <- remap_internal_nodes(rebuilt_edges[, 1L])
    rebuilt_edges[, 2L] <- remap_internal_nodes(rebuilt_edges[, 2L])

    rebuilt_lengths <- phy$edge.length[keep_edges]
    half_outgroup_length <- outgroup_length / 2

    out_phy <- phy
    out_phy$edge <- rbind(
        c(new_root, shifted_old_root),
        c(new_root, outgroup_tip),
        rebuilt_edges
    )
    out_phy$edge.length <- c(
        half_outgroup_length,
        half_outgroup_length,
        rebuilt_lengths
    )
    out_phy$Nnode <- nnode + 1L
    out_phy$root.edge <- NULL

    if (!is.null(phy$node.label)) {
        out_phy$node.label <- c("", phy$node.label)
    }

    out_phy <- ape::reorder.phylo(out_phy, order = "cladewise")
    newick <- ape::write.tree(out_phy, digits = digits)

    if (write) {
        if (is.null(file)) {
            if (is.null(input_file)) {
                stop(
                    "`file` must be supplied when `write = TRUE` and ",
                    "`tree` is not a file path."
                )
            }
            file <- file.path(
                dirname(input_file),
                paste0(
                    tools::file_path_sans_ext(basename(input_file)),
                    ".bi.treefile"
                )
            )
        }

        if (!is.character(file) ||
            length(file) != 1L ||
            is.na(file) ||
            identical(file, "")) {
            stop("`file` must be a single non-empty character string.")
        }

        out_dir <- dirname(file)
        if (!dir.exists(out_dir)) {
            stop("Output directory does not exist: ", out_dir)
        }
        if (file.exists(file) && !overwrite) {
            stop(
                "Output file already exists. Use `overwrite = TRUE` to ",
                "replace it: ", file
            )
        }

        writeLines(newick, file)
        if (verbose) {
            message("Output written to: ", file)
        }
    }

    if (identical(return, "newick")) {
        return(newick)
    }
    if (identical(return, "phylo")) {
        return(out_phy)
    }

    treeio::as.treedata(out_phy)
}
